# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Shyyko Serhiy
tagline:             'small things'
description:         'You can reach me out on <a href="https://github.com/shyykoserhiy">github</a>, <a
href="https://linkedin.com/in/shyykoserhiy">linkedin</a> or by <a href="mailto:shyyko.serhiy@gmail.com">email</a>.'
url:                 http://shyyko.com
baseurl:             /
paginate:            5
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


# About/contact
author:
  name:              Shyyko Serhiy
  url:               http://shyyko.com
  email:             shyyko.serhiy@gmail.com
